from academic_service.models.models_branch import Branch
from academic_service.models.models_branch_address import BranchAddress
from academic_service.models.models_direction import Direction
from academic_service.models.models_education_plans import EducationPlan
from academic_service.models.models_education_plan_modules import EducationPlanModule
from academic_service.models.module import Module
from academic_service.models.models_group import Group
from academic_service.models.models_group_member import GroupMember